# SPDX-License-Identifier: LGPL-3.0-or-later
"""
Backward compatibility shim for argument_parser.py

This module has been split into focused submodules under cli/args/.
All symbols are re-exported here for backward compatibility.

New code should import from cli.args directly:
    from hyper2kvm.cli.args import build_parser, parse_args_with_config
"""
from __future__ import annotations

# Re-export everything from the args package for backward compatibility
from .args import (
    HelpFormatter,
    _add_ami_extraction_knobs,
    _add_azure_knobs,
    _add_daemon_flags,
    _add_domain_emission,
    _add_fixing_behavior,
    _add_flatten_convert,
    _add_global_config_logging,
    _add_global_operation_flags,
    _add_govc_knobs,
    _add_input_paths,
    _add_luks_knobs,
    _add_ovf_ova_knobs,
    _add_ovftool_knobs,
    _add_project_control,
    _add_ssh_fetch_knobs,
    _add_systemd_gen,
    _add_tests,
    _add_batch_knobs,
    _add_vsphere_core_knobs,
    _add_vsphere_export_and_download_knobs,
    _add_windows_network_override,
    _add_windows_virtio_definitions,
    _build_epilog,
    _build_preparser,
    _load_merged_config,
    _materialize_virtio_config_json_if_needed,
    _materialize_win_net_json_if_needed,
    _merged_cmd,
    _merged_get,
    _merged_secret,
    _merged_vs_action,
    _pick_vsphere_vm_name,
    _require,
    _require2,
    _resolve_workdir,
    _validate_cmd_ami,
    _validate_cmd_azure,
    _validate_cmd_fetch_and_fix,
    _validate_cmd_live_fix,
    _validate_cmd_local,
    _validate_cmd_ova,
    _validate_cmd_ovf,
    _validate_cmd_vhd,
    _validate_cmd_vsphere,
    _validate_json_object_file,
    _validate_json_object_inline,
    _validate_virtio_config_inputs,
    _validate_vsphere_action_requirements,
    _validate_vsphere_control_plane,
    _validate_vsphere_download_transport,
    _validate_vsphere_identity,
    _validate_win_net_override_inputs,
    build_parser,
    parse_args_with_config,
    validate_args,
)

__all__ = [
    "HelpFormatter",
    "_add_ami_extraction_knobs",
    "_add_azure_knobs",
    "_add_daemon_flags",
    "_add_domain_emission",
    "_add_fixing_behavior",
    "_add_flatten_convert",
    "_add_global_config_logging",
    "_add_global_operation_flags",
    "_add_govc_knobs",
    "_add_input_paths",
    "_add_luks_knobs",
    "_add_ovf_ova_knobs",
    "_add_ovftool_knobs",
    "_add_project_control",
    "_add_ssh_fetch_knobs",
    "_add_systemd_gen",
    "_add_tests",
    "_add_batch_knobs",
    "_add_vsphere_core_knobs",
    "_add_vsphere_export_and_download_knobs",
    "_add_windows_network_override",
    "_add_windows_virtio_definitions",
    "_build_epilog",
    "_build_preparser",
    "_load_merged_config",
    "_materialize_virtio_config_json_if_needed",
    "_materialize_win_net_json_if_needed",
    "_merged_cmd",
    "_merged_get",
    "_merged_secret",
    "_merged_vs_action",
    "_pick_vsphere_vm_name",
    "_require",
    "_require2",
    "_resolve_workdir",
    "_validate_cmd_ami",
    "_validate_cmd_azure",
    "_validate_cmd_fetch_and_fix",
    "_validate_cmd_live_fix",
    "_validate_cmd_local",
    "_validate_cmd_ova",
    "_validate_cmd_ovf",
    "_validate_cmd_vhd",
    "_validate_cmd_vsphere",
    "_validate_json_object_file",
    "_validate_json_object_inline",
    "_validate_virtio_config_inputs",
    "_validate_vsphere_action_requirements",
    "_validate_vsphere_control_plane",
    "_validate_vsphere_download_transport",
    "_validate_vsphere_identity",
    "_validate_win_net_override_inputs",
    "build_parser",
    "parse_args_with_config",
    "validate_args",
]
